<a href="https://colab.research.google.com/github/smitapatil1/Hypothesis-1/blob/main/buyer_ratio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import scipy.stats as stats
import pandas as pd
from scipy.stats import chi2_contingency

In [ ]:
buyer_ratio= pd.read_csv("/content/BuyerRatio (1).csv")

In [ ]:
buyer_ratio

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

Null hypothesis (H0):- All proportions are equal

Alternative hypothesis (H1): Not all propotions are equal

Test to be used:-Chi-square test



In [ ]:
#contingency table
table = np.array([[50, 142, 131, 70], [435, 1523, 1356, 750]])
print(table)

[[  50  142  131   70]
 [ 435 1523 1356  750]]


In [ ]:

stat, p, dof, expected=stats.chi2_contingency(table)
print(stat)
print(p)
print(dof)
print(expected)



1.595945538661058
0.6603094907091882
3
[[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


p-value obtained from the chi-square test is greater than the significance level (commonly set to 0.05), we accept the null hypothesis and conclude that there is evidence that the male-female buyer ratios are similar across regions.